import * as React from "react";

/**
 * Union type of all available icon names
 * This will be auto-generated during the build process
 */

export type IconName =
  | 'AcuraIcon'
  | 'AcuraLogoHorizontal'
  | 'AcuraLogo'
  | 'AcuraWordmark'
  | 'AlfaRomeoIcon'
  | 'AlfaRomeoLogoHorizontal'
  | 'AlfaRomeoLogo'
  | 'AlfaRomeoWordmark'
  | 'AstonMartinIcon'
  | 'AstonMartinLogoHorizontal'
  | 'AstonMartinLogo'
  | 'AstonMartinWordmark'
  | 'AudiIcon'
  | 'AudiLogoHorizontal'
  | 'AudiLogo'
  | 'AudiWordmark'
  | 'BMWIcon'
  | 'BMWLogoHorizontal'
  | 'BMWLogo'
  | 'BMWWordmark'
  | 'BYDIcon'
  | 'BYDLogoHorizontal'
  | 'BYDLogo'
  | 'BYDWordmark'
  | 'BentleyIcon'
  | 'BentleyLogoHorizontal'
  | 'BentleyLogo'
  | 'BentleyWordmark'
  | 'CadillacIcon'
  | 'CadillacLogoHorizontal'
  | 'CadillacLogo'
  | 'CadillacWordmark'
  | 'ChevroletIcon'
  | 'ChevroletLogoHorizontal'
  | 'ChevroletLogo'
  | 'ChevroletWordmark'
  | 'ChryslerIcon'
  | 'ChryslerLogoHorizontal'
  | 'ChryslerLogo'
  | 'ChryslerWordmark'
  | 'DodgeIcon'
  | 'DodgeLogoHorizontal'
  | 'DodgeLogo'
  | 'DodgeWordmark'
  | 'FerrariIcon'
  | 'FerrariLogoHorizontal'
  | 'FerrariLogo'
  | 'FerrariWordmark'
  | 'FiatIcon'
  | 'FiatLogoHorizontal'
  | 'FiatLogo'
  | 'FiatWordmark'
  | 'FordIcon'
  | 'FordLogoHorizontal'
  | 'FordLogo'
  | 'FordWordmark'
  | 'GMCIcon'
  | 'GMCLogoHorizontal'
  | 'GMCLogo'
  | 'GMCWordmark'
  | 'GenesisIcon'
  | 'GenesisLogoHorizontal'
  | 'GenesisLogo'
  | 'GenesisWordmark'
  | 'HondaIcon'
  | 'HondaLogoHorizontal'
  | 'HondaLogo'
  | 'HondaWordmark'
  | 'HummerIcon'
  | 'HummerLogoHorizontal'
  | 'HummerLogo'
  | 'HummerWordmark'
  | 'HyundaiIcon'
  | 'HyundaiLogoHorizontal'
  | 'HyundaiLogo'
  | 'HyundaiWordmark'
  | 'InfinitiIcon'
  | 'InfinitiLogoHorizontal'
  | 'InfinitiLogo'
  | 'InfinitiWordmark'
  | 'JaguarIcon'
  | 'JaguarLogoHorizontal'
  | 'JaguarLogo'
  | 'JaguarWordmark'
  | 'JeepIcon'
  | 'JeepLogoHorizontal'
  | 'JeepLogo'
  | 'JeepWordmark'
  | 'KiaIcon'
  | 'KiaLogoHorizontal'
  | 'KiaLogo'
  | 'KiaWordmark'
  | 'LamborghiniIcon'
  | 'LamborghiniLogoHorizontal'
  | 'LamborghiniLogo'
  | 'LamborghiniWordmark'
  | 'LandroverIcon'
  | 'LandroverLogoHorizontal'
  | 'LandroverLogo'
  | 'LandroverWordmark'
  | 'LexusIcon'
  | 'LexusLogoHorizontal'
  | 'LexusLogo'
  | 'LexusWordmark'
  | 'LincolnIcon'
  | 'LincolnLogoHorizontal'
  | 'LincolnLogo'
  | 'LincolnWordmark'
  | 'LotusIcon'
  | 'LotusLogoHorizontal'
  | 'LotusLogo'
  | 'LotusWordmark'
  | 'LucidIcon'
  | 'LucidLogoHorizontal'
  | 'LucidLogo'
  | 'LucidWordmark'
  | 'MBIcon'
  | 'MBLogoHorizontal'
  | 'MBLogo'
  | 'MBWordmark'
  | 'MaseratiIcon'
  | 'MaseratiLogoHorizontal'
  | 'MaseratiLogo'
  | 'MaseratiWordmark'
  | 'MazdaIcon'
  | 'MazdaLogoHorizontal'
  | 'MazdaLogo'
  | 'MazdaWordmark'
  | 'MclarenIcon'
  | 'MclarenLogoHorizontal'
  | 'MclarenLogo'
  | 'MclarenWordmark'
  | 'MiniIcon'
  | 'MiniLogoHorizontal'
  | 'MiniLogo'
  | 'MiniWordmark'
  | 'MitsubishiIcon'
  | 'MitsubishiLogoHorizontal'
  | 'MitsubishiLogo'
  | 'MitsubishiWordmark'
  | 'NissanIcon'
  | 'NissanLogoHorizontal'
  | 'NissanLogo'
  | 'NissanWordmark'
  | 'PolestarIcon'
  | 'PolestarLogoHorizontal'
  | 'PolestarLogo'
  | 'PolestarWordmark'
  | 'PorscheIcon'
  | 'PorscheLogoHorizontal'
  | 'PorscheLogo'
  | 'PorscheWordmark'
  | 'RAMIcon'
  | 'RAMLogoHorizontal'
  | 'RAMLogo'
  | 'RAMWordmark'
  | 'RollsRoyceIcon'
  | 'RollsRoyceLogoHorizontal'
  | 'RollsRoyceLogo'
  | 'RollsRoyceWordmark'
  | 'SubaruIcon'
  | 'SubaruLogoHorizontal'
  | 'SubaruLogo'
  | 'SubaruWordmark'
  | 'TeslaIcon'
  | 'TeslaLogoHorizontal'
  | 'TeslaLogo'
  | 'TeslaWordmark'
  | 'ToyotaIcon'
  | 'ToyotaLogoHorizontal'
  | 'ToyotaLogo'
  | 'ToyotaWordmark'
  | 'VinfastIcon'
  | 'VinfastLogoHorizontal'
  | 'VinfastLogo'
  | 'VinfastWordmark'
  | 'VolkswagenIcon'
  | 'VolkswagenLogoHorizontal'
  | 'VolkswagenLogo'
  | 'VolkswagenWordmark'
  | 'VolvoIcon'
  | 'VolvoLogoHorizontal'
  | 'VolvoLogo'
  | 'VolvoWordmark';

/**
 * Props for the Icon component
 */
export interface IconProps extends React.SVGProps<SVGSVGElement> {
  /** The name of the icon to display */
  name: IconName;
  /** Size of the icon (both width and height) */
  size?: number | string;
  /** Color of the icon */
  color?: string;
}

/**
 * SVG props with ref forwarding
 */
export type IconComponentProps = React.SVGProps<SVGSVGElement>;
